### ISSUE TITLE
Are new docs being deployed to VHEGA site?

### ISSUE THREAD

**Issue by morcuended** [juanep97/iop4#89]
I think they still point to a previous version. I do not see the example gallery.

We could also link that docs page to the readme

**Comment by juanep97** [comment]
No, they are not being deployed. I will manually deploy them (and make it public, it still requires login). We might want to set up a different place for the stable relase documentation, any idea?

**Comment by juanep97** [comment]
I don't think the examples can be run in the readthedocs build step.

**Comment by morcuended** [comment]
To be checked, but I would say that it's possible

**Comment by morcuended** [comment]
or even using GitHub pages

**Comment by juanep97** [comment]
> or even using GitHub pages

I think this is the safest option? Just adding the deployement to github pages at the end of the docs job in ci.yml.

**Comment by morcuended** [comment]
Ok, I see, then serving it to github pages
